Fail the build early if imageTag is not set and set proper names hey

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,4 +1,4 @@
-name: snomio-$(Date:yyyyMMdd)$(Rev:.r)_$(Build.SourceBranchName)
+name: snomio-$(Date:yyyyMMdd)$(Rev:.r)_$(Build.Sourcepostfix)
 
 trigger:
   - main
@@ -24,14 +24,14 @@ jobs:
     steps:
       - script: |
           if [[ "$(Build.SourceBranch)" =~ refs/heads/(.+) ]]; then
-            branchName=${BASH_REMATCH[1]}
-            imageTag="${Build.BuildId}_${branchName}"
+            # Direct branch build
+            postfix=""
           elif [[ "$(Build.SourceBranch)" =~ refs/pull/[0-9]+/merge ]]; then
-            branchName=${SYSTEM_PULLREQUEST_SOURCEBRANCH#refs/heads/}
-            imageTag="snomio-$(Build.BuildNumber)_${branchName}_PR"
+            postfix="_${SYSTEM_PULLREQUEST_SOURCEBRANCH#refs/heads/}"
           else
-            imageTag="snomio-$(Build.BuildNumber)_unknown"
+            postfix="_unknown"
           fi
+          imageTag="$(Build.BuildNumber)_$postfix"
           imageTag=${imageTag//\//-}
           imageTag=${imageTag//#/}
           echo "##vso[task.setvariable variable=imageTag]$imageTag"
@@ -59,6 +59,10 @@ jobs:
 
       - script: |
           imageTag=$(cat $(Pipeline.Workspace)/branchInfo/branchInfo.txt)
+          if [[ -z "$imageTag" || "$imageTag" == *unknown* ]]; then
+            echo "Invalid imageTag: $imageTag"
+            exit 1
+          fi
           echo "##vso[task.setvariable variable=imageTag]$imageTag"
           echo "Using imageTag: $imageTag"
         displayName: 'Read imageTag from branchInfo.txt'
@@ -120,6 +124,10 @@ jobs:
 
       - script: |
           imageTag=$(cat $(Pipeline.Workspace)/branchInfo/branchInfo.txt)
+          if [[ -z "$imageTag" || "$imageTag" == *unknown* ]]; then
+            echo "Invalid imageTag: $imageTag"
+            exit 1
+          fi
           echo "##vso[task.setvariable variable=imageTag]$imageTag"
           echo "Using imageTag: $imageTag"
         displayName: 'Read imageTag from branchInfo.txt'
@@ -225,6 +233,10 @@ jobs:
 
       - script: |
           imageTag=$(cat $(Pipeline.Workspace)/branchInfo/branchInfo.txt)
+          if [[ -z "$imageTag" || "$imageTag" == *unknown* ]]; then
+            echo "Invalid imageTag: $imageTag"
+            exit 1
+          fi
           echo "##vso[task.setvariable variable=imageTag]$imageTag"
           echo "Using imageTag: $imageTag"
         displayName: 'Read imageTag from branchInfo.txt'
